// map-demo.mjs — 演示房源 fixture（C3 内部 seam）。decision 字段由 scripts/lib/decision.mjs 的 decide() 语义预计算，
// selftest 断言两者一致；页面经 JSON 注入消费，不承载分层语义。
export const DEMO_HOUSES = [
      {
        report_no: "001",
        community: "演示小区·壹（虚构）",
        city: "上海",
        district: "浦东金桥",
        type: "二手住宅",
        total_price_wan: 535,
        unit_price: 51200,
        area_sqm: 104.5,
        score_global: 4.3,
        hard_dq_hit: false,
        risk_tier: "low",
        conclusion: "worth_viewing",
        policy_tax_wan: 8.5,
        policy_lock_risk: "满五唯一，契税1.5%，无增值税，学位未占用（锁定风险低）",
        market_trend: "bottoming",
        market_trend_text: "较2021高点回调24%，近半年成交均价筑底平稳",
        discount_space: "normal",
        discount_space_text: "同类户型实际成交相较挂牌折价 3-5% (议价约15-25万)",
        liquidity_rating: "年均换手22套，平均去化65天，流动性良好",
        urban_planning: "positive",
        urban_planning_text: "轨交21号线在建（距金桥站约700m，预计2027通车），金桥副中心产业辐射",
        urban_planning_env: "周边无新增高密住宅抛压，东侧规划社区体育公园已批复",
        marketing_claim: "中介宣称'紧邻轨交枢纽，对口名校，绝版好房抢手'",
        verified_fact: "已交叉验证：实测步行至21号线在建站约700m，非现成上盖；对口小学办学仅3年并非名校；但满五唯一与筑底折价属实",
        tradeoff_summary: "【优势】自住品质与户型极佳，筑底期议价空间健康；【代价】单价贴近预算上限，需承担2年轨交施工期噪音。",
        decision: { tier: "rec", markerCls: "high", tag: "可约看", tagCls: "status-green", risk: "低" },
        coords: [121.6112, 31.2586]
      },
      {
        report_no: "002",
        community: "演示小区·贰（虚构）",
        city: "上海",
        district: "浦东金桥",
        type: "二手住宅",
        total_price_wan: 480,
        unit_price: 46000,
        area_sqm: 104.3,
        score_global: 3.8,
        hard_dq_hit: false,
        risk_tier: "caution",
        conclusion: "conditional",
        policy_tax_wan: 15.2,
        policy_lock_risk: "满二不唯一（个税核定2%），需多付约9.6万个税；学位五年一户已用2年",
        market_trend: "declining",
        market_trend_text: "较峰值回调31%，近3个月仍有以价换量迹象",
        discount_space: "wide",
        discount_space_text: "在售库存多，挂牌折价弹性达 6-8% (可大胆砍价30万+)",
        liquidity_rating: "挂牌周期长达110天，买方市场特征显著",
        urban_planning: "neutral",
        urban_planning_text: "周边无新建重大轨交规划，依赖既有9号线台儿庄路站(950m)",
        urban_planning_env: "南侧为成熟居住区，无变数也无新增红利",
        marketing_claim: "房东急售笋盘，低于市场价30万，送全套家具软装",
        verified_fact: "已交叉验证：二楼独立排水未改造有返水隐患，且近3个月同户型成交均价460万，480万并无明显倒挂，非真实笋盘",
        tradeoff_summary: "【优势】总价更低且房东急售折价弹性大，低门槛上车；【代价】税费较高且学位受限，抗跌性稍弱。",
        decision: { tier: "cond", markerCls: "mid", tag: "备选对照", tagCls: "status-blue", risk: "注意" },
        coords: [121.5980, 31.2650]
      },
      {
        report_no: "003",
        community: "演示小区·叁（虚构）",
        city: "上海",
        district: "浦东高行",
        type: "动迁混居住宅",
        total_price_wan: 420,
        unit_price: 41000,
        area_sqm: 102.4,
        score_global: 3.2,
        hard_dq_hit: true,
        risk_tier: "high",
        conclusion: "pass",
        policy_tax_wan: 6.3,
        policy_lock_risk: "动迁安置满三年，免增值税，税费负担轻",
        market_trend: "declining",
        market_trend_text: "跑输大盘，受周边次新商品房挤压，流通性钝化",
        discount_space: "wide",
        discount_space_text: "议价弹性大但带看极冷清（近30天仅2次）",
        liquidity_rating: "去化困难，属于潜在流动性陷阱",
        urban_planning: "uncertain",
        urban_planning_text: "紧邻规划货运铁路联络线，远期面临重载列车噪音",
        urban_planning_env: "西侧为已批建垃圾中转站扩建工程，存在嫌恶设施隐患",
        marketing_claim: "宣称'总价低至420万，超大赠送面积，未来绿地环绕'",
        verified_fact: "已交叉验证：赠送部位属违建私封北天井，有拆除风险；西侧法定控规为垃圾中转站而非绿地，营销虚假承诺",
        tradeoff_summary: "【优势】绝对总价最低(420万)；【代价】命中硬性DQ（噪音超标+回迁混居），未来转手与居住体验风险过大。",
        decision: { tier: "pass", markerCls: "low", tag: "高代价/已排除", tagCls: "status-red", risk: "高" },
        coords: [121.6030, 31.2950]
      },
      {
        report_no: "004",
        community: "演示小区·肆（虚构）",
        city: "上海",
        district: "浦东碧云",
        type: "二手国际社区",
        total_price_wan: 780,
        unit_price: 68000,
        area_sqm: 115.0,
        score_global: 4.6,
        hard_dq_hit: true,
        risk_tier: "low",
        conclusion: "pass",
        policy_tax_wan: 19.5,
        policy_lock_risk: "非普通住宅（单价超标），差额增值税与契税双高",
        market_trend: "bottoming",
        market_trend_text: "板块极其抗跌，近2年仅微调8%，圈层与外籍承租需求稳固",
        discount_space: "tight",
        discount_space_text: "业主心态极强，折价空间通常仅 1-2%",
        liquidity_rating: "优质房源放出一周内秒去化",
        urban_planning: "positive",
        urban_planning_text: "碧云国际社区核心成熟区，9/14号线双轨交环绕",
        urban_planning_env: "绿化率高，无任何嫌恶设施规划",
        marketing_claim: "纯正涉外国际社区，保值抗跌首选",
        verified_fact: "已交叉验证：抗跌性与国际圈层属实，但总价超出用户预算上限180万，税费极高，属画像硬性不符",
        tradeoff_summary: "【优势】圈层与自住品质天花板；【代价】总价超出预算180万触发硬性DQ，仅作为品质标杆方案对照。",
        decision: { tier: "pass", markerCls: "low", tag: "高代价/已排除", tagCls: "status-red", risk: "低" },
        coords: [121.5850, 31.2420]
      }
    ];;
